#ifndef MODULE_CONFIG_HPP
#define MODULE_CONFIG_HPP

#define APPLICATION_NAME "TemperatureSensor A01"

#define APPLICATION_NUMBER_OF_SENSORS 4

#define APPLICATION_DATA_PUSH_TIME_INTERVAL 25000

#define SERVER_IP_ADDRESS 52, 14, 123, 233
#define SERVER_HOST_NAME "http://api.asksensors.com"
#define SERVER_API_KEY "9sF8ibj8KSB8Qvdh3XQlp2dnd1ufutRj"

#endif